### ISSUE TITLE
rancher + traefik infinite restart

### ISSUE THREAD

**Issue by samouds** [rawmind0/rancher-traefik#43]
Hello,

I'm using traefik with rancher :
rawmind/alpine-traefik:1.2.1
rawmind/rancher-traefik:0.3.4-19
rancher 1.5.3

Here is my docker compose file :
```
traefik:
  user: root
  privileged: true
  ports:
  - ${admin_port}:8000/tcp
  - ${http_port}:${http_port}/tcp
  - ${https_port}:${https_port}/tcp
  log_driver: ''
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: traefik-conf
    io.rancher.container.hostname_override: container_name
  tty: true
  log_opt: {}
  image: rawmind/alpine-traefik:1.2.1
  environment:
  - CONF_INTERVAL=${refresh_interval}
  - TRAEFIK_HTTP_PORT=${http_port}
  - TRAEFIK_HTTPS_ENABLE=${https_enable}
  - TRAEFIK_HTTPS_PORT=${https_port}
  - TRAEFIK_ADMIN_PORT=${admin_port}
  - TRAEFIK_ACME_ENABLE=${acme_enable}
  - TRAEFIK_ACME_EMAIL=${acme_email}
  - TRAEFIK_ACME_ONDEMAND=${acme_ondemand}
  - TRAEFIK_ACME_ONHOSTRULE=${acme_onhostrule}
  volumes_from:
  - traefik-conf

traefik-conf:
  user: root
  privileged: true
  log_driver: ''
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: 'lb=true'
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.start_once: 'true'
  tty: true
  log_opt: {}
  image: rawmind/rancher-traefik:0.3.4-19
  net: none
  volumes:
    - /mnt/data/traefik/opt/tools:/opt/tools
    - /mnt/data/traefik/opt/certs:/opt/certs
    - /mnt/data/traefik/opt/acme:/opt/acme
```

And when I check the logs I get several times : 

```
11/04/2017 11:48:18'traefik' process is not running
11/04/2017 11:48:18'traefik' trying to restart
11/04/2017 11:48:18'traefik' start: '/opt/traefik/bin/traefik-service.sh start'
11/04/2017 11:48:18Tue Apr 11 09:48:18 UTC 2017 - [ Generating traefik configuration... ]
11/04/2017 11:48:18Tue Apr 11 09:48:18 UTC 2017 - [ Redirecting traefik log... ]
11/04/2017 11:48:18Tue Apr 11 09:48:18 UTC 2017 - [ Redirecting traefik log... ]
11/04/2017 11:48:18Tue Apr 11 09:48:18 UTC 2017 - [ Starting traefik... ]
11/04/2017 11:48:18nohup: appending output to nohup.out
11/04/2017 11:48:18time="2017-04-11T09:48:18Z" level=info msg="Traefik version v1.2.1 built on 2017-03-27_03:33:41PM"
11/04/2017 11:48:18time="2017-04-11T09:48:18Z" level=info msg="Using TOML configuration file /opt/traefik/etc/traefik.toml"
11/04/2017 11:48:18time="2017-04-11T09:48:18Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc42053d3e0 Auth:<nil> Compress:false}"
11/04/2017 11:48:18time="2017-04-11T09:48:18Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4203704e0 Redirect:<nil> Auth:<nil> Compress:false}"
11/04/2017 11:48:18time="2017-04-11T09:48:18Z" level=info msg="Starting server on :80"
11/04/2017 11:48:18time="2017-04-11T09:48:18Z" level=fatal msg="Error creating server: listen tcp :80: bind: address already in use"


11/04/2017 11:56:21time="2017-04-11T09:56:21Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc420252cc0 Redirect:<nil> Auth:<nil> Compress:false}"
11/04/2017 11:56:22time="2017-04-11T09:56:22Z" level=info msg="Loading ACME Account..."
11/04/2017 11:56:22time="2017-04-11T09:56:22Z" level=warning msg="Remove duplicate cert: {Main:***MYDOMAIN*** SANs:[]}, expiration :2017-07-10 08:43:00 +0000 UTC"
11/04/2017 11:56:22time="2017-04-11T09:56:22Z" level=warning msg="Remove duplicate cert: {Main:***MYDOMAIN*** SANs:[]}, expiration :2017-07-10 08:43:00 +0000 UTC"
11/04/2017 11:56:22time="2017-04-11T09:56:22Z" level=info msg="Loaded ACME config from store /opt/traefik/acme/acme.json"
11/04/2017 11:56:23time="2017-04-11T09:56:23Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc42020cc30 Auth:<nil> Compress:false}"
11/04/2017 11:56:23time="2017-04-11T09:56:23Z" level=info msg="Starting server on :443"
11/04/2017 11:56:23time="2017-04-11T09:56:23Z" level=info msg="Starting provider *provider.File {\"Watch\":true,\"Filename\":\"/opt/traefik/etc/rules.toml\",\"Constraints\":null}"
11/04/2017 11:56:23time="2017-04-11T09:56:23Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8000\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Statistics\":null,\"Metrics\":null,\"Auth\":null}"
11/04/2017 11:56:23time="2017-04-11T09:56:23Z" level=fatal msg="Error creating server: listen tcp :443: bind: address already in use"
11/

```

I'm wondering if it's normal.
