### ISSUE TITLE
Service with zero containers causes template issue

### ISSUE THREAD

**Issue by davidnortonjr** [rawmind0/rancher-traefik#49]
When we have a service with zero containers (e.g., it failed to start or something), confd stops updating and throws this error in the logs:

```
2017-07-13T11:10:53Z routing-traefik-1 /opt/tools/confd/bin/confd[22]: ERROR template: rules.toml.tmpl:41:34: executing "rules.toml.tmpl" at <getv (printf "/stack...>: error calling getv: key does not exist
```

To reproduce, launch a stack (but **uncheck the box `Start services after creating`**) with the following `docker-compose.yml`

```
version: '2'
services:
  zerotest:
    image: nginx:latest
    labels:
      traefik.enable: 'true'
      traefik.alias: zerotest
      traefik.port: '80'
      traefik.domain: doesnotmatter
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
```

and rancher-compose.yml:

```
version: '2'
services:
  zerotest:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
```

I have a pull request to fix this: https://github.com/rawmind0/rancher-traefik/pull/48

The issue was occurring on `rancher-traefik:0.3.4-19`.
