### ISSUE TITLE
can't expose multiple ports

### ISSUE THREAD

**Issue by kneufeld** [rawmind0/rancher-traefik#60]
Thank you for providing this otherwise very easy to use template for rancher.

After reading the docker backend docs, the service name [overrides](https://docs.traefik.io/configuration/backends/docker/#on-service) where exactly what I was looking for to expose multiple ports in my service.

So it was sad pandas all around when I realized that the rancher backend doesn't support multiple services.

Here's the `labels` section from my `docker-compose.yml` in my attempts to get this working. In case it matters, nothing is actually listening on port 9999 in my container. Without the `traefik.port` line my admin page in traefic is empty as mentioned in lots of other github issues.

```
labels:
    traefik.enable: 'true'
    traefik.domain: local
    traefik.port: '9999'                                     # tried with and without this line
    traefik.weblistener.port: '5000'
    traefik.weblistener.frontend.rule: Host:foo.example.com
    traefik.websocket.port: '5001'
    traefik.websocket.frontend.rule: Host:bar.example.com
    traefik.director.port: '3013'
    traefik.director.frontend.rule: Host:baz.example.com
```

Since rancher is mostly just a pretty wrapper around docker I don't understand why the rancher backend is missing functionality from the docker backend?
